services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: networker
      POSTGRES_USER: networker
      POSTGRES_PASSWORD: networker
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
