-- Initial schema. Mirrors the JPA entities in com.goat.demo.domain; Hibernate validates against it on startup.

create table profiles (
    id             uuid                        not null,
    auth0_id       varchar(255)                not null,
    name           varchar(255),
    headline       varchar(255),
    location       varchar(255),
    bio            varchar(2000),
    email          varchar(255),
    picture_url    text,
    portfolio_url  varchar(300),
    hide_location  boolean                     not null default false,
    hide_email     boolean                     not null default false,
    created_at     timestamp(6) with time zone not null,
    constraint pk_profiles primary key (id),
    constraint uq_profiles_auth0_id unique (auth0_id)
);

create table profile_interests (
    profile_id  uuid        not null,
    interest    varchar(40),
    constraint fk_profile_interests_profile foreign key (profile_id) references profiles (id)
);

create index ix_profile_interests_profile on profile_interests (profile_id);

create table connections (
    id            bigint generated by default as identity,
    requester_id  uuid                        not null,
    addressee_id  uuid                        not null,
    status        varchar(255)                not null,
    created_at    timestamp(6) with time zone not null,
    accepted_at   timestamp(6) with time zone,
    constraint pk_connections primary key (id),
    constraint uq_connections_pair unique (requester_id, addressee_id),
    constraint ck_connections_status check (status in ('PENDING', 'ACCEPTED')),
    constraint fk_connections_requester foreign key (requester_id) references profiles (id),
    constraint fk_connections_addressee foreign key (addressee_id) references profiles (id)
);

create index ix_connections_addressee on connections (addressee_id);

create table notes (
    id          bigint generated by default as identity,
    author_id   uuid                        not null,
    subject_id  uuid                        not null,
    body        text                        not null,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    constraint pk_notes primary key (id),
    constraint fk_notes_author foreign key (author_id) references profiles (id),
    constraint fk_notes_subject foreign key (subject_id) references profiles (id)
);

create index ix_notes_author_subject on notes (author_id, subject_id);
create index ix_notes_subject on notes (subject_id);

create table meetings (
    id           bigint generated by default as identity,
    owner_id     uuid                        not null,
    attendee_id  uuid,
    title        varchar(255)                not null,
    starts_at    timestamp(6) with time zone not null,
    ends_at      timestamp(6) with time zone not null,
    location     varchar(255),
    description  varchar(2000),
    constraint pk_meetings primary key (id),
    constraint fk_meetings_owner foreign key (owner_id) references profiles (id),
    constraint fk_meetings_attendee foreign key (attendee_id) references profiles (id)
);

create index ix_meetings_owner_starts on meetings (owner_id, starts_at);
create index ix_meetings_attendee_starts on meetings (attendee_id, starts_at);
