-- Tells people when the other person in a meeting invites, changes, accepts, declines or cancels it.
-- meeting_id has no foreign key on purpose: the notification outlives a cancelled meeting.

create table notifications (
    id              bigint generated by default as identity,
    recipient_id    uuid                        not null,
    actor_id        uuid                        not null,
    type            varchar(255)                not null,
    meeting_id      bigint,
    title           varchar(255)                not null,
    previous_title  varchar(255),
    starts_at       timestamp(6) with time zone not null,
    location        varchar(255),
    changes         varchar(255),
    created_at      timestamp(6) with time zone not null,
    read_at         timestamp(6) with time zone,
    constraint pk_notifications primary key (id),
    constraint ck_notifications_type check (type in ('INVITED', 'UPDATED', 'CANCELLED', 'ACCEPTED', 'DECLINED')),
    constraint fk_notifications_recipient foreign key (recipient_id) references profiles (id),
    constraint fk_notifications_actor foreign key (actor_id) references profiles (id)
);

create index ix_notifications_recipient_created on notifications (recipient_id, created_at);
