-- Meetings can have several attendees, each answering the invitation on their own.
-- Moves the single attendee_id / invite_status pair off meetings into its own table.

create table meeting_attendees (
    id          bigint generated by default as identity,
    meeting_id  bigint       not null,
    profile_id  uuid         not null,
    status      varchar(255) not null,
    constraint pk_meeting_attendees primary key (id),
    constraint uq_meeting_attendees_meeting_profile unique (meeting_id, profile_id),
    constraint ck_meeting_attendees_status check (status in ('PENDING', 'ACCEPTED')),
    constraint fk_meeting_attendees_meeting foreign key (meeting_id) references meetings (id) on delete cascade,
    constraint fk_meeting_attendees_profile foreign key (profile_id) references profiles (id)
);

create index ix_meeting_attendees_profile on meeting_attendees (profile_id);

insert into meeting_attendees (meeting_id, profile_id, status)
select id, attendee_id, coalesce(invite_status, 'ACCEPTED') from meetings where attendee_id is not null;

alter table meetings drop constraint fk_meetings_attendee;
alter table meetings drop constraint ck_meetings_invite_status;
drop index ix_meetings_attendee_starts;
alter table meetings drop column attendee_id;
alter table meetings drop column invite_status;

-- An attendee who declines a group meeting just drops out; the organizer hears they can't make it.
alter table notifications drop constraint ck_notifications_type;
alter table notifications add constraint ck_notifications_type
    check (type in ('INVITED', 'UPDATED', 'CANCELLED', 'ACCEPTED', 'DECLINED', 'DROPPED_OUT'));
